service: beers-list

frameworkVersion: ">=1.28.0 <2.0.0"

plugins:
  - serverless-domain-manager

custom:
  active:       ${file(../../conf.${self:provider.stage}.yml):conf}
  customDomain: ${file(../../conf.${self:provider.stage}.yml):pickingDomain}
  serviceName:  beers-list

provider:
  name: aws
  runtime: go1.x
  stage:   ${opt:stage, 'dev'}
  region:  us-east-1
  memorySize: 1024
  deploymentBucket:
    name: ${self:custom.active.deployment_bucket}
  deploymentPrefix: ${self:custom.active.deployment_prefix}
  environment:
    DYNAMODB_BEERS:               ${self:custom.active.dynamodb_beers}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:${self:custom.active.account}:table/${self:custom.active.dynamodb_beers}
        - arn:aws:dynamodb:${self:provider.region}:${self:custom.active.account}:table/${self:custom.active.dynamodb_beers}/index/*

resources:
  Resources:
    V1LogGroup:
      Properties:
        RetentionInDays: ${self:custom.active.log_retention}

package:
  individually: true
  exclude:
    - ./**

functions:
  v1:
    handler: bin/v1
    package:
      include:
        - ./bin/v1
    timeout: 30
    events:
      - http:
          path: v1
          method: get

