// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/dynamodb"
	"github.com/chandy20/prueba-smartjobandina/beer/list/v1/internal/ctx"
	"github.com/sirupsen/logrus"
)

// Injectors from wire.go:

func Initialize() (*ctx.Handler, error) {
	v := providerAWSConfig()
	sessionSession, err := session.NewSession(v...)
	if err != nil {
		return nil, err
	}
	dynamoDB := dynamodb.New(sessionSession, v...)
	logger := logrus.New()
	beerRepository, err := providerBeerRepository(dynamoDB, logger)
	if err != nil {
		return nil, err
	}
	handler := provideNewHandler(beerRepository, logger)
	return handler, nil
}
